spring:
  application:
    name: product-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888

    
server:
  port: 8082
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
 
  
  
